spring:
  application:
    name: mylog

  datasource:
#    url: jdbc:mysql://localhost:3306/mylog
#    username: root
#    password: 1234
     url: ${SPRING_DATASOURCE_URL}
     username: ${SPRING_DATASOURCE_USERNAME}
     password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope:
              - email
              - profile
jwt:
  issuer: abc@gmail.com
  secret_key: study-springboot

